### Game Settings
armor_material_crystal = false
armor_material_nether = false

tech_enable_recipes = true

ghost_purge_max_inactivity = 90

i3_progressive_mode = false

creatura_mapgen_spawning = false
creatura_spawn_interval = 60
creatura_mapblock_limit = 6
creatura_abr_limit = 12

mobs_attack_creatura = true
anvil_hammer_is_repairable = false

log_non_player_actions = false

protector_flip = true