### Game Settings
armor_material_crystal = false
armor_material_nether = false

tech_enable_recipes = true

ghost_purge_max_inactivity = 90

i3_progressive_mode = false

creatura_mapgen_spawning = false
creatura_spawn_interval = 60
creatura_mapblock_limit = 6
creatura_abr_limit = 12
creatura_min_abm_dist = 48
creatura_a_star_alloted_time = 350
creatura_theta_star_alloted_time = 450

animalia_common_chance = 60000
animalia_ambient_chance = 25000
animalia_pest_chance = 15000
animalia_predator_chance = 50000

mobs_spawn_protected = false
mob_node_timer_interval = 0.5
mob_main_timer_interval = 1.5
mob_chance_multiplier = 2.0
mob_active_limit = 24
mob_area_spawn = true
mob_nospawn_range = 18.0
mob_difficulty = 1.15

mobs_attack_creatura = true
anvil_hammer_is_repairable = false

log_non_player_actions = false

protector_flip = true

default_use_current_sounds = false