[BOT]
token = MTM1OTgzOTk2MjE5MDcwODgzOA.GZobkq.C7PKOGI0SU9J0dWYN6eucCMkjRiilMW-EqMLhY
command_prefix = !
[RELAY]
port = 8080
channel_id = 1359839378645585981
allow_logins = true
clean_invites = true
use_nicknames = true

# Uncomment to send messages to Discord every 3 seconds (for busy servers)
# send_every_3s = true