name = i3
description = Next-generation inventory
optional_depends = 3d_armor, skins, awards, moreores, ethereal, nether, xpanes, stainedglass
min_minetest_version = 5.4
title = i3
release = 36702
author = mt-mods
