name = moreores
description = Adds new ore types.
depends = default
optional_depends = farming, frame
min_minetest_version = 5.0.0
supported_games = minetest_game
title = More Ores
release = 28903
author = Calinou
